### PR TITLE
Add Investigator.percentage

### PR DESCRIPTION
**Pull request by rtfeldman**
I wanted one of these so I could generate an Array and then select an element from within it at random. Seems more broadly applicable than that, of course. :smiley:

### CODE REVIEW

**Comment by TheSeamau5** [comment]
Oh, quick tip, if you want a random generator that always generates the same value, there's `constant`.

http://package.elm-lang.org/packages/TheSeamau5/elm-random-extra/2.1.0/Random-Extra#constant

**Comment by rtfeldman** [comment]
Ah! Good to know. I figured there was something like that, but didn't know what it was called. Changed to `constant` in c69d079a0df116d9adf9601afd4a7dbfd2f5824f

**Comment by TheSeamau5** [comment]
Cool, thanks. This is a pretty useful investigator.

**Comment by TheSeamau5** [comment]
Published : http://package.elm-lang.org/packages/TheSeamau5/elm-check/3.1.0/Check-Investigator#percentage

**Comment by rtfeldman** [comment]
Nice, thanks! :grinning:

**Pull request merged**
